### ISSUE TITLE
Top Bar Should Remain when Scrolling so the User can View their Cart and Compare List

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#177] opened 2017-03-01 01:14 UTC
This was suggested during the user survey. Currently, the top bar navigation does not stay at the top of the screen when the user is scrolling through page results. So the user has to scroll all the way up if they want to use compare list or see their cart. This top bar navigation should remain locked at the top of the screen.

**Comment by neelusingh28** [comment] 2017-03-01 22:46
Top navigation is remain only in Chrome but NOT in IE & Firefox.

**Comment by christianhfei** [comment] 2017-03-01 23:59
Seems to work fine in IE and Firefox, please make sure you clear your cache and do a hard refresh when confirming.

**Comment by neelusingh28** [comment] 2017-03-02 14:51
Top navigation is remain now in Chrome, IE & Firefox but NOT in devices - Galaxy, iPhone 6, iPad,

**Comment by jennymnh** [comment] 2017-03-02 18:17
This was design as intended. If you have a sticky top navigation it takes up too much space on the screen and you would only have half a screen to view your content.

**Comment by neelusingh28** [comment] 2017-03-02 18:39
All right closing then.

**Closed as completed by neelusingh28** 2017-03-02 18:39 UTC
Labels: 4 - Done
