### ISSUE TITLE
Home Page Stock Art Needs to Be Revised

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#132] opened 2017-02-24 14:48 UTC
The current images of generic products imply that we have sales and seem to be directed towards a more generic consumer rather than a government buyer. Can we replace these items with stock art of IT workers, people working on computers, people pulling stock from warehouses.

**Comment by kcallander** [comment] 2017-02-27 19:12
These have been updated and new layouts need to be reviewed and approved.

**Comment by jennymnh** [comment] 2017-02-28 21:50
Images have been revised and I have pushed my changes. The issue is related to #117 so I am closing this one.

**Closed as completed** 2017-03-01 04:39 UTC
Labels: 4 - Done
