### ISSUE TITLE
Required fields for entering items to catalog

### ISSUE THREAD

**Issue by llin-freeman** [FEISystems/ca-adpq-prototype#141] opened 2017-02-24 19:42 UTC
When entering or importing items to the catalog, please make the UNSPSC field not a required field.

**Comment by ClaireReinken** [comment] 2017-03-01 16:13
Duplicate of Issue #150

**Comment by ClaireReinken** [comment] 2017-03-01 16:29
Not duplicate

**Comment by davidatfei** [comment] 2017-03-02 01:59
UNSPSC is no longer required

**Comment by lutech** [comment] 2017-03-02 17:26
@neelusingh28 , I also added visual form validation to make it easier to know what is required.

**Comment by neelusingh28** [comment] 2017-03-02 17:34
Browser: Chrome
logged in as Admin 1

1. Go to Add product> entered all fields except UNSPSC > Click on Add item > Add item does nothing.

**Comment by davidatfei** [comment] 2017-03-02 18:07
Cannot reproduce. Works as expected. Please provide more detail if you are still having trouble.

**Comment by lutech** [comment] 2017-03-02 18:13
Was able to reproduce. It has been resolved.

**Comment by neelusingh28** [comment] 2017-03-02 21:58
Verified and Passed in 5000 site and working as expected in Chrome, Firefox and IE.

**Closed as completed by neelusingh28** 2017-03-02 21:58 UTC
Labels: 4 - Done
